esphome:
  name: test-casa-luigi
#  platformio_options:
#    board_build.flash_mode: dio

# Enable logging
logger:

# Enable Home Assistant API
api:

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    - esp32_ble_tracker.start_scan:
        continuous: true
  on_disconnect:
    - esp32_ble_tracker.stop_scan:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    continuous: false

bluetooth_proxy:
  active: True

ota:
  platform: esphome
